name: clone

on:
  workflow_dispatch:
jobs:
  job_clone:
    name: Clone
    runs-on: ubuntu-latest
    steps:
      - name: testing
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            ssh-keyscan -H github.com >> ~${{ secrets.USERNAME }}/.ssh/known_hosts
            cd ../pub
            git clone git@github.com:venkatgokaraju/venkatgokaraju.github.io.git