name: deployment workflow
on:
  push:
    branches: [main]
jobs:
  job_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: pull dir
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd venkatgokaraju.github.io
            git pull